import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { VisualEditing } from "next-sanity";

import ScrollToTopButton from "@/components/ScrollToTopButton";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ChatWrapper from "@/components/ChatWrapper"; 

export const metadata: Metadata = {
  title: "TrendyFit",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const draft = await draftMode();

  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          {draft.isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
          <main className="pt-20">
            <Header />
            {children}
            <ChatWrapper />
            <ScrollToTopButton />
            <Footer />
          </main>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
